import { Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { CREATE_TABLES_SQL } from './schema';

export interface IDatabase {
  execAsync(query: string): Promise<void>;
  runAsync(
    statement: string,
    ...params: any[]
  ): Promise<{ changes: number; lastInsertRowId: number }>;
  getAllAsync<T = any>(statement: string, ...params: any[]): Promise<T[]>;
  getFirstAsync<T = any>(
    statement: string,
    ...params: any[]
  ): Promise<T | null>;
}

/**
 * Robust Persistent AsyncStorage Database Fallback.
 *
 * Used when native Expo SQLite is unavailable, such as:
 * - Expo Go
 * - Web
 * - environments where expo-sqlite native bindings are unavailable
 *
 * This implements the small subset of SQL used by SmritiCare's
 * local repositories.
 */
class PersistentDatabaseFallback implements IDatabase {
  private tables: Map<string, any[]> = new Map();
  private loaded = false;

  private tableNames = [
    'local_game_results',
    'local_cognitive_scores',
    'local_memories',
    'local_tasks',
    'local_user_profile',
    'sync_queue',
  ];

  constructor() {
    for (const name of this.tableNames) {
      this.tables.set(name, []);
    }
  }

  async init(): Promise<void> {
    if (this.loaded) {
      return;
    }

    try {
      for (const name of this.tableNames) {
        const stored = await AsyncStorage.getItem(
          `@smriticare_db_${name}`,
        );

        if (stored) {
          try {
            const parsed = JSON.parse(stored);

            this.tables.set(
              name,
              Array.isArray(parsed) ? parsed : [],
            );
          } catch {
            this.tables.set(name, []);
          }
        } else {
          this.tables.set(name, []);
        }
      }

      this.loaded = true;
    } catch (error) {
      console.warn(
        'PersistentDatabaseFallback: error reading AsyncStorage',
        error,
      );

      this.loaded = true;
    }
  }

  private async persistTable(tableName: string): Promise<void> {
    try {
      const data = this.tables.get(tableName) || [];

      await AsyncStorage.setItem(
        `@smriticare_db_${tableName}`,
        JSON.stringify(data),
      );
    } catch (error) {
      console.warn(
        `PersistentDatabaseFallback: error persisting table ${tableName}`,
        error,
      );
    }
  }

  /**
   * Converts a SQL literal into a JavaScript value.
   *
   * This method is intentionally defensive because the fallback parser
   * receives SQL generated by several repositories.
   */
  private parseLiteral(value: string | undefined): any {
    if (value === undefined || value === null) {
      return undefined;
    }

    const normalized = String(value).trim();

    if (!normalized) {
      return '';
    }

    if (normalized.toUpperCase() === 'NULL') {
      return null;
    }

    if (normalized.toUpperCase() === 'TRUE') {
      return true;
    }

    if (normalized.toUpperCase() === 'FALSE') {
      return false;
    }

    const numericValue = Number(normalized);

    if (!Number.isNaN(numericValue)) {
      return numericValue;
    }

    return normalized.replace(/^['"]|['"]$/g, '');
  }

  async execAsync(query: string): Promise<void> {
    await this.init();

    // Tables are created automatically by the fallback storage engine.
    // Native SQLite handles CREATE TABLE statements separately.
    void query;
  }

  async runAsync(
    statement: string,
    ...params: any[]
  ): Promise<{ changes: number; lastInsertRowId: number }> {
    await this.init();

    const cleanSql = statement.replace(/\s+/g, ' ').trim();

    // ============================================================
    // INSERT
    // ============================================================

    const insertMatch = cleanSql.match(
      /^INSERT\s+INTO\s+([a-zA-Z0-9_]+)\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)/i,
    );

    if (insertMatch) {
      const tableName = insertMatch[1];
      const colNames = insertMatch[2]
        .split(',')
        .map((column) => column.trim());

      const valPlaceholders = insertMatch[3]
        .split(',')
        .map((value) => value.trim());

      let paramIdx = 0;

      const row: Record<string, any> = {};

      for (let i = 0; i < colNames.length; i++) {
        const col = colNames[i];

        // IMPORTANT:
        // Do not assume valPlaceholders[i] always exists.
        const placeholder = valPlaceholders[i];

        if (placeholder === '?') {
          row[col] = params[paramIdx++];
        } else {
          row[col] = this.parseLiteral(placeholder);
        }
      }

      const tableData = this.tables.get(tableName) || [];

      // Upsert simulation for rows having an id.
      if (row.id !== undefined && row.id !== null) {
        const existingIdx = tableData.findIndex(
          (existingRow) => existingRow.id === row.id,
        );

        if (existingIdx >= 0) {
          tableData[existingIdx] = {
            ...tableData[existingIdx],
            ...row,
          };
        } else {
          tableData.push(row);
        }
      } else if (
        tableName === 'local_user_profile' &&
        row.user_id !== undefined &&
        row.user_id !== null
      ) {
        const existingIdx = tableData.findIndex(
          (existingRow) =>
            existingRow.user_id === row.user_id,
        );

        if (existingIdx >= 0) {
          tableData[existingIdx] = {
            ...tableData[existingIdx],
            ...row,
          };
        } else {
          tableData.push(row);
        }
      } else {
        tableData.push(row);
      }

      this.tables.set(tableName, tableData);

      await this.persistTable(tableName);

      return {
        changes: 1,
        lastInsertRowId: tableData.length,
      };
    }

    // ============================================================
    // UPDATE
    // ============================================================

    const updateMatch = cleanSql.match(
      /^UPDATE\s+([a-zA-Z0-9_]+)\s+SET\s+(.+?)(?:\s+WHERE\s+(.+))?$/i,
    );

    if (updateMatch) {
      const tableName = updateMatch[1];
      const setClause = updateMatch[2];
      const whereClause = updateMatch[3];

      const tableData = this.tables.get(tableName) || [];

      let paramIdx = 0;

      const assignments = setClause
        .split(',')
        .map((item) => item.trim())
        .filter(Boolean);

      const updatesToApply: Record<string, any> = {};

      let incrementRetryCount = false;

      for (const assignment of assignments) {
        const equalsIndex = assignment.indexOf('=');

        if (equalsIndex === -1) {
          continue;
        }

        const col = assignment
          .slice(0, equalsIndex)
          .trim();

        const val = assignment
          .slice(equalsIndex + 1)
          .trim();

        if (!col) {
          continue;
        }

        if (val === '?') {
          updatesToApply[col] = params[paramIdx++];
          continue;
        }

        if (
          /^retry_count\s*\+\s*1$/i.test(
            `${col} + ${val}`,
          ) ||
          /^retry_count\s*\+\s*1$/i.test(
            `${col}=${val}`,
          )
        ) {
          incrementRetryCount = true;
          continue;
        }

        if (
          /^retry_count\s*\+\s*1$/i.test(
            val.replace(/\s+/g, ''),
          )
        ) {
          incrementRetryCount = true;
          continue;
        }

        updatesToApply[col] = this.parseLiteral(val);
      }

      // The SET clause has consumed paramIdx parameters.
      // WHERE parameters must start from that position.
      let updatedCount = 0;

      for (let i = 0; i < tableData.length; i++) {
        let matches = true;

        if (whereClause) {
          matches = this.evaluateWhere(
            tableData[i],
            whereClause,
            params,
            paramIdx,
          );
        }

        if (!matches) {
          continue;
        }

        const updatedRow = {
          ...tableData[i],
          ...updatesToApply,
        };

        if (incrementRetryCount) {
          updatedRow.retry_count =
            (updatedRow.retry_count || 0) + 1;
        }

        tableData[i] = updatedRow;
        updatedCount++;
      }

      this.tables.set(tableName, tableData);

      await this.persistTable(tableName);

      return {
        changes: updatedCount,
        lastInsertRowId: 0,
      };
    }

    // ============================================================
    // DELETE
    // ============================================================

    const deleteMatch = cleanSql.match(
      /^DELETE\s+FROM\s+([a-zA-Z0-9_]+)(?:\s+WHERE\s+(.+))?$/i,
    );

    if (deleteMatch) {
      const tableName = deleteMatch[1];
      const whereClause = deleteMatch[2];

      let tableData = this.tables.get(tableName) || [];

      if (!whereClause) {
        const changes = tableData.length;

        this.tables.set(tableName, []);

        await this.persistTable(tableName);

        return {
          changes,
          lastInsertRowId: 0,
        };
      }

      const initialLength = tableData.length;

      tableData = tableData.filter(
        (row) =>
          !this.evaluateWhere(
            row,
            whereClause,
            params,
            0,
          ),
      );

      this.tables.set(tableName, tableData);

      await this.persistTable(tableName);

      return {
        changes: initialLength - tableData.length,
        lastInsertRowId: 0,
      };
    }

    return {
      changes: 0,
      lastInsertRowId: 0,
    };
  }

  async getAllAsync<T = any>(
    statement: string,
    ...params: any[]
  ): Promise<T[]> {
    await this.init();

    const cleanSql = statement.replace(/\s+/g, ' ').trim();

    // ============================================================
    // SELECT COUNT(*)
    // ============================================================

    if (
      /SELECT\s+COUNT\(\*\)\s+as\s+count/i.test(
        cleanSql,
      )
    ) {
      const tableMatch = cleanSql.match(
        /FROM\s+([a-zA-Z0-9_]+)(?:\s+WHERE\s+(.+))?/i,
      );

      if (tableMatch) {
        const tableName = tableMatch[1];
        const whereClause = tableMatch[2];

        const tableData =
          this.tables.get(tableName) || [];

        if (!whereClause) {
          return [
            { count: tableData.length },
          ] as T[];
        }

        const filtered = tableData.filter(
          (row) =>
            this.evaluateWhere(
              row,
              whereClause,
              params,
              0,
            ),
        );

        return [
          { count: filtered.length },
        ] as T[];
      }

      return [{ count: 0 }] as T[];
    }

    // ============================================================
    // NORMAL SELECT
    // ============================================================

    const selectMatch = cleanSql.match(
      /SELECT\s+(.+?)\s+FROM\s+([a-zA-Z0-9_]+)(?:\s+WHERE\s+(.+?))?(?:\s+ORDER\s+BY\s+(.+?))?(?:\s+LIMIT\s+(.+?))?$/i,
    );

    if (!selectMatch) {
      return [];
    }

    const selectCols = selectMatch[1].trim();
    const tableName = selectMatch[2].trim();

    const whereClause = selectMatch[3]
      ? selectMatch[3].trim()
      : undefined;

    const orderByClause = selectMatch[4]
      ? selectMatch[4].trim()
      : undefined;

    const limitClause = selectMatch[5]
      ? selectMatch[5].trim()
      : undefined;

    let rows = [
      ...(this.tables.get(tableName) || []),
    ];

    // ============================================================
    // FILTER
    // ============================================================

    if (whereClause) {
      rows = rows.filter((row) =>
        this.evaluateWhere(
          row,
          whereClause,
          params,
          0,
        ),
      );
    }

    // ============================================================
    // SORT
    // ============================================================

    if (orderByClause) {
      const [orderCol, orderDir] =
        orderByClause.split(/\s+/);

      const isDesc =
        !!orderDir &&
        orderDir.toUpperCase() === 'DESC';

      rows.sort((a, b) => {
        const valueA = a[orderCol] ?? '';
        const valueB = b[orderCol] ?? '';

        if (valueA < valueB) {
          return isDesc ? 1 : -1;
        }

        if (valueA > valueB) {
          return isDesc ? -1 : 1;
        }

        return 0;
      });
    }

    // ============================================================
    // LIMIT
    // ============================================================

    if (limitClause) {
      let limitNum = Number(limitClause);

      if (limitClause === '?') {
        const limitParam =
          params[params.length - 1];

        if (
          typeof limitParam === 'number' &&
          Number.isFinite(limitParam)
        ) {
          limitNum = limitParam;
        }
      }

      if (
        !Number.isNaN(limitNum) &&
        limitNum > 0
      ) {
        rows = rows.slice(0, limitNum);
      }
    }

    // ============================================================
    // COLUMN ALIASES
    // ============================================================

    if (selectCols !== '*') {
      const colMappers = selectCols
        .split(',')
        .map((column) => {
          const parts = column
            .trim()
            .split(/\s+as\s+/i);

          const original = parts[0].trim();

          const alias = parts[1]
            ? parts[1].trim()
            : original;

          return {
            original,
            alias,
          };
        });

      return rows.map((row) => {
        const mapped: Record<string, any> = {};

        for (const mapper of colMappers) {
          mapped[mapper.alias] =
            row[mapper.original] !== undefined
              ? row[mapper.original]
              : row[mapper.alias];
        }

        return mapped as T;
      });
    }

    return rows as T[];
  }

  async getFirstAsync<T = any>(
    statement: string,
    ...params: any[]
  ): Promise<T | null> {
    const all = await this.getAllAsync<T>(
      statement,
      ...params,
    );

    return all.length > 0 ? all[0] : null;
  }

  /**
   * Evaluates the limited WHERE syntax used by the
   * local repositories.
   */
  private evaluateWhere(
    row: Record<string, any>,
    whereClause: string,
    params: any[],
    paramOffset: number,
  ): boolean {
    const cleanWhere = whereClause
      .split(/\s+ORDER\s+BY/i)[0]
      .split(/\s+LIMIT/i)[0]
      .trim();

    if (!cleanWhere) {
      return true;
    }

    const conditions = cleanWhere
      .split(/\s+AND\s+/i)
      .map((condition) => condition.trim())
      .filter(Boolean);

    let paramIndex = paramOffset;

    for (const condition of conditions) {
      const match = condition.match(
        /^([a-zA-Z0-9_]+)\s*(=|!=|<>|<=|>=|<|>)\s*(.+)$/i,
      );

      if (!match) {
        continue;
      }

      const col = match[1];
      const op = match[2];
      const rawValue = match[3]
        ? match[3].trim()
        : '';

      let targetValue: any;

      if (rawValue === '?') {
        targetValue = params[paramIndex++];
      } else {
        targetValue =
          this.parseLiteral(rawValue);
      }

      const actualValue = row[col];

      if (op === '=') {
        if (
          String(actualValue) !==
          String(targetValue)
        ) {
          return false;
        }
      } else if (
        op === '!=' ||
        op === '<>'
      ) {
        if (
          String(actualValue) ===
          String(targetValue)
        ) {
          return false;
        }
      } else if (op === '<') {
        if (!(actualValue < targetValue)) {
          return false;
        }
      } else if (op === '>') {
        if (!(actualValue > targetValue)) {
          return false;
        }
      } else if (op === '<=') {
        if (!(actualValue <= targetValue)) {
          return false;
        }
      } else if (op === '>=') {
        if (!(actualValue >= targetValue)) {
          return false;
        }
      }
    }

    return true;
  }
}

let dbInstance: IDatabase | null = null;
let isInitialized = false;

/**
 * Initializes the SQLite database or transparent
 * persistent AsyncStorage fallback.
 */
export async function initDatabase(): Promise<IDatabase> {
  if (isInitialized && dbInstance) {
    return dbInstance;
  }

  // Persistent AsyncStorage storage engine for Expo Go, Native, and Web
  const fallback = new PersistentDatabaseFallback();
  await fallback.init();

  dbInstance = fallback;
  isInitialized = true;

  return fallback;
}

/**
 * Gets the current database instance.
 */
export async function getDatabase(): Promise<IDatabase> {
  if (!isInitialized || !dbInstance) {
    return initDatabase();
  }

  return dbInstance;
}